-- ============================================
-- PAYMENT SPLIT & ROUTING SYSTEM
-- ============================================
-- Platform commission to owner's Paystack
-- Product price to seller's account
-- Version: 1.0
-- Date: November 17, 2025
-- ============================================

-- ============================================
-- 1. PLATFORM PAYSTACK ACCOUNTS
-- ============================================

CREATE TABLE IF NOT EXISTS platform_paystack_accounts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    
    -- Account Type
    account_type VARCHAR(50) NOT NULL UNIQUE CHECK (
        account_type IN ('commission', 'transaction_fees', 'subscription', 'ads')
    ),
    
    -- Paystack Details
    subaccount_code VARCHAR(100) NOT NULL UNIQUE, -- Paystack subaccount code
    account_name VARCHAR(255) NOT NULL,
    settlement_bank VARCHAR(100),
    account_number VARCHAR(50),
    
    -- Split Percentage (for split payments)
    default_percentage DECIMAL(5,2), -- e.g., 5.00 for 5%
    
    -- Status
    is_active BOOLEAN DEFAULT true,
    
    -- Metadata
    total_received DECIMAL(15,2) DEFAULT 0.00,
    transaction_count INTEGER DEFAULT 0,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert platform accounts (run once)
INSERT INTO platform_paystack_accounts (account_type, subaccount_code, account_name, default_percentage) VALUES
    ('commission', 'SUBACCT_commission', 'ShopUp Commission Account', 5.00),
    ('transaction_fees', 'SUBACCT_fees', 'ShopUp Transaction Fees', 0.00),
    ('subscription', 'SUBACCT_subscription', 'ShopUp Subscriptions', 0.00),
    ('ads', 'SUBACCT_ads', 'ShopUp Advertising Revenue', 0.00)
ON CONFLICT (account_type) DO NOTHING;

-- ============================================
-- 2. SELLER PAYSTACK ACCOUNTS
-- ============================================

CREATE TABLE IF NOT EXISTS seller_paystack_accounts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    seller_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    
    -- Paystack Subaccount
    subaccount_code VARCHAR(100) UNIQUE, -- Generated by Paystack
    subaccount_id VARCHAR(100), -- Paystack subaccount ID
    
    -- Bank Details
    settlement_bank VARCHAR(100) NOT NULL,
    account_number VARCHAR(50) NOT NULL,
    account_name VARCHAR(255) NOT NULL,
    
    -- Mobile Money (Alternative)
    momo_provider VARCHAR(50),
    momo_number VARCHAR(20),
    momo_account_name VARCHAR(255),
    
    -- Preferred Settlement
    preferred_method VARCHAR(50) DEFAULT 'bank' CHECK (preferred_method IN ('bank', 'momo')),
    
    -- Status
    is_verified BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    
    -- Verification
    verified_at TIMESTAMP WITH TIME ZONE,
    verification_method VARCHAR(50), -- 'paystack_api', 'manual'
    
    -- Metadata
    total_received DECIMAL(15,2) DEFAULT 0.00,
    last_payout_at TIMESTAMP WITH TIME ZONE,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_seller_paystack_seller ON seller_paystack_accounts(seller_id);
CREATE INDEX idx_seller_paystack_subaccount ON seller_paystack_accounts(subaccount_code);

-- ============================================
-- 3. PAYMENT SPLITS (Per Transaction)
-- ============================================

CREATE TABLE IF NOT EXISTS payment_splits (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    
    -- Transaction Reference
    payment_transaction_id UUID NOT NULL REFERENCES payment_transactions(id) ON DELETE CASCADE,
    order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    
    -- Total Breakdown
    total_amount DECIMAL(10,2) NOT NULL,
    product_price DECIMAL(10,2) NOT NULL,
    delivery_fee DECIMAL(10,2) DEFAULT 0.00,
    
    -- Platform Share (Service Fee)
    commission_rate DECIMAL(5,2) NOT NULL, -- From seller's subscription
    commission_amount DECIMAL(10,2) NOT NULL,
    transaction_fee DECIMAL(10,2) NOT NULL, -- GH₵0.30 or percentage
    platform_total DECIMAL(10,2) NOT NULL, -- commission + transaction_fee
    
    -- Seller Share
    seller_amount DECIMAL(10,2) NOT NULL, -- product_price + delivery_fee
    
    -- Paystack Split Details
    paystack_split_code VARCHAR(100), -- Paystack split payment code
    
    -- Settlement Status
    platform_settled BOOLEAN DEFAULT false,
    platform_settled_at TIMESTAMP WITH TIME ZONE,
    
    seller_settled BOOLEAN DEFAULT false,
    seller_settled_at TIMESTAMP WITH TIME ZONE,
    
    -- References
    platform_subaccount VARCHAR(100), -- Where platform money goes
    seller_subaccount VARCHAR(100), -- Where seller money goes
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_payment_splits_transaction ON payment_splits(payment_transaction_id);
CREATE INDEX idx_payment_splits_order ON payment_splits(order_id);

-- ============================================
-- 4. SETTLEMENT TRACKING
-- ============================================

CREATE TABLE IF NOT EXISTS settlements (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    
    -- Recipient
    recipient_type VARCHAR(50) NOT NULL CHECK (recipient_type IN ('platform', 'seller')),
    recipient_id UUID, -- seller_id if seller
    
    -- Settlement Details
    settlement_type VARCHAR(50) NOT NULL CHECK (
        settlement_type IN ('order_payment', 'subscription', 'ad_revenue', 'withdrawal')
    ),
    amount DECIMAL(10,2) NOT NULL,
    
    -- Paystack Details
    paystack_subaccount VARCHAR(100) NOT NULL,
    paystack_transfer_code VARCHAR(100),
    paystack_reference VARCHAR(255),
    
    -- Status
    status VARCHAR(50) DEFAULT 'pending' CHECK (
        status IN ('pending', 'processing', 'completed', 'failed', 'reversed')
    ),
    
    -- Error Handling
    failure_reason TEXT,
    retry_count INTEGER DEFAULT 0,
    
    -- Dates
    scheduled_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    processed_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_settlements_recipient ON settlements(recipient_id);
CREATE INDEX idx_settlements_status ON settlements(status);
CREATE INDEX idx_settlements_type ON settlements(settlement_type);

-- ============================================
-- PAYMENT SPLIT LOGIC FUNCTION
-- ============================================

CREATE OR REPLACE FUNCTION calculate_payment_split(
    p_order_id UUID,
    p_total_amount DECIMAL
)
RETURNS TABLE(
    product_price DECIMAL,
    delivery_fee DECIMAL,
    commission_rate DECIMAL,
    commission_amount DECIMAL,
    transaction_fee DECIMAL,
    platform_total DECIMAL,
    seller_amount DECIMAL
) AS $$
DECLARE
    v_order RECORD;
    v_subscription RECORD;
    v_product_total DECIMAL;
    v_delivery DECIMAL;
    v_commission_rate DECIMAL;
    v_commission DECIMAL;
    v_tx_fee DECIMAL;
    v_platform DECIMAL;
    v_seller DECIMAL;
BEGIN
    -- Get order details
    SELECT o.*, 
           COALESCE(o.delivery_fee, 0) as del_fee,
           (o.total_amount - COALESCE(o.delivery_fee, 0)) as prod_total
    INTO v_order
    FROM orders o
    WHERE o.id = p_order_id;
    
    -- Get seller's commission rate from subscription
    SELECT sp.commission_rate
    INTO v_commission_rate
    FROM seller_subscriptions ss
    JOIN subscription_plans sp ON ss.plan_id = sp.id
    WHERE ss.seller_id = v_order.seller_id
    AND ss.status IN ('trial', 'active');
    
    -- Default to 5% if no subscription
    v_commission_rate := COALESCE(v_commission_rate, 5.00);
    
    -- Calculate splits
    v_product_total := v_order.prod_total;
    v_delivery := v_order.del_fee;
    
    -- Commission on product price only (not delivery)
    v_commission := ROUND((v_product_total * v_commission_rate / 100), 2);
    
    -- Transaction fee (flat GH₵0.30)
    v_tx_fee := 0.30;
    
    -- Platform gets: commission + transaction fee
    v_platform := v_commission + v_tx_fee;
    
    -- Seller gets: product price + delivery fee
    v_seller := v_product_total + v_delivery;
    
    RETURN QUERY SELECT
        v_product_total,
        v_delivery,
        v_commission_rate,
        v_commission,
        v_tx_fee,
        v_platform,
        v_seller;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- CREATE PAYMENT SPLIT ON ORDER
-- ============================================

CREATE OR REPLACE FUNCTION create_payment_split()
RETURNS TRIGGER AS $$
DECLARE
    v_split RECORD;
    v_platform_subaccount VARCHAR;
    v_seller_subaccount VARCHAR;
BEGIN
    -- Only process when payment is successful
    IF NEW.payment_status = 'successful' THEN
        
        -- Calculate split
        SELECT * INTO v_split
        FROM calculate_payment_split(NEW.order_id, NEW.amount);
        
        -- Get platform subaccount
        SELECT subaccount_code INTO v_platform_subaccount
        FROM platform_paystack_accounts
        WHERE account_type = 'commission'
        AND is_active = true;
        
        -- Get seller subaccount
        SELECT subaccount_code INTO v_seller_subaccount
        FROM seller_paystack_accounts spa
        JOIN orders o ON o.seller_id = spa.seller_id
        WHERE o.id = NEW.order_id;
        
        -- Insert split record
        INSERT INTO payment_splits (
            payment_transaction_id,
            order_id,
            total_amount,
            product_price,
            delivery_fee,
            commission_rate,
            commission_amount,
            transaction_fee,
            platform_total,
            seller_amount,
            platform_subaccount,
            seller_subaccount
        ) VALUES (
            NEW.id,
            NEW.order_id,
            NEW.amount,
            v_split.product_price,
            v_split.delivery_fee,
            v_split.commission_rate,
            v_split.commission_amount,
            v_split.transaction_fee,
            v_split.platform_total,
            v_split.seller_amount,
            v_platform_subaccount,
            v_seller_subaccount
        );
        
        -- Create settlement records
        -- Platform settlement
        INSERT INTO settlements (
            recipient_type,
            settlement_type,
            amount,
            paystack_subaccount,
            status
        ) VALUES (
            'platform',
            'order_payment',
            v_split.platform_total,
            v_platform_subaccount,
            'pending'
        );
        
        -- Seller settlement
        INSERT INTO settlements (
            recipient_type,
            recipient_id,
            settlement_type,
            amount,
            paystack_subaccount,
            status
        ) VALUES (
            'seller',
            (SELECT seller_id FROM orders WHERE id = NEW.order_id),
            'order_payment',
            v_split.seller_amount,
            v_seller_subaccount,
            'pending'
        );
        
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_create_payment_split ON payment_transactions;
CREATE TRIGGER trigger_create_payment_split
    AFTER INSERT OR UPDATE ON payment_transactions
    FOR EACH ROW
    EXECUTE FUNCTION create_payment_split();

-- ============================================
-- PAYSTACK INTEGRATION GUIDE
-- ============================================

COMMENT ON TABLE payment_splits IS 'Tracks how payments are split between platform and sellers';
COMMENT ON TABLE settlements IS 'Tracks actual money transfers to platform and seller accounts';

COMMENT ON FUNCTION calculate_payment_split IS 'Calculates split: Platform gets commission+fee, Seller gets product price+delivery';

-- ============================================
-- EXAMPLE CALCULATION
-- ============================================

/*
EXAMPLE ORDER:
Product Price: GH₵100
Delivery Fee: GH₵10
Total: GH₵110

Seller on Essential Plan (3% commission)

SPLIT:
- Commission: GH₵100 × 3% = GH₵3.00
- Transaction Fee: GH₵0.30
- Platform Total: GH₵3.00 + GH₵0.30 = GH₵3.30
- Seller Total: GH₵100 + GH₵10 = GH₵110

Buyer pays: GH₵110 + GH₵3.30 = GH₵113.30

PAYSTACK SPLIT:
- To Platform Subaccount: GH₵3.30
- To Seller Subaccount: GH₵110
*/

-- ============================================
-- SUCCESS MESSAGE
-- ============================================

DO $$
BEGIN
    RAISE NOTICE '✅ Payment Split System Created!';
    RAISE NOTICE '💰 Platform commission goes to your Paystack account';
    RAISE NOTICE '💵 Seller payment goes to their account';
    RAISE NOTICE '🔄 Automatic split on every transaction';
    RAISE NOTICE '';
    RAISE NOTICE '📋 Next Steps:';
    RAISE NOTICE '1. Create Paystack subaccounts for platform';
    RAISE NOTICE '2. Sellers add their bank/MoMo details';
    RAISE NOTICE '3. Paystack Split Payment API handles routing';
END $$;
